AuctionModule/Models/Auction.cs
using System;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;

namespace AuctionModule.Models
{
    public class Auction
    {
        public long Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }
        [Required]
        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }
        [Required]
        [DataType(DataType.DateTime)]

        public DateTime StartTime { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime EndTime { get; set; }
        [DataType(DataType.Currency)]
        public decimal? CurrentPrice { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public decimal StartPrice { get; set; }

        public string Category { get; set; }
        public virtual Collection<Bid> Bids { get; private set; }

        public int Bidcount
        {
            get { return Bids.Count; }
        }

        public Auction()
        {
            Bids = new Collection<Bid>();

        }

    }
}

AuctionModule/Models/AuctionContext.cs
using System.Data.Entity;

namespace AuctionModule.Models
{
    public class AuctionContext : DbContext
    {
        public AuctionContext() : base("name=constr")
        {

        }
        public DbSet<Auction> Auctions { get; set; }
        public DbSet<Bid> Bids { get; set; }
    }
}

AuctionModule/Models/Bid.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AuctionModule.Models
{
    public class Bid
    {
        public long Id { get; set; }
        public long AuctionId { get; set; }
        [Required]
        public DateTime TimeStamp { get; set; }

        public string UserName { get; set; }
        [Range(1, double.MaxValue)]
        public decimal Amount { get; set; }

        public Bid()
        {
            TimeStamp = DateTime.Now;
        }


    }
}

AuctionModule/Controllers/AuctionsController.cs
using AuctionModule.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AuctionModule.Controllers
{
    public class AuctionsController : Controller
    {
        // GET: Auctions
        public ActionResult Index()
        {
            AuctionContext db = new AuctionContext();
            List<Auction> auctions = db.Auctions.ToList();
            return View(auctions);
        }

        public ActionResult FindingBy(long id)
        {
            AuctionContext db = new AuctionContext();
            var auction = db.Auctions.Find(id);
            return View(auction);
        }
        [HttpGet]
        public ActionResult Auction()
        {
            var categoryList = new SelectList(new[] { "Games", "Mobiles", "Movies", "Drinks", "Fabrics" });
            ViewBag.cate = categoryList;
            return View();
        }
        [HttpPost]
        public ActionResult Auction([Bind(Exclude = "CurrentPrice")]Auction auction)
        {
            //if (string.IsNullOrWhiteSpace(auction.Title))
            //{
            //    ModelState.AddModelError("Title", "Title Must  be Required");
            //}
            //else if (auction.Title.Length < 5 || auction.Title.Length > 200)
            //{
            //    ModelState.AddModelError("Title", "Your Title Must be Greater Then 5 and Less then 200 char");
            //}

            if (ModelState.IsValid)
            {
                AuctionContext db = new AuctionContext();
                using (db)
                {
                    db.Auctions.Add(auction);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpPost]
        public ActionResult Bid(Bid bid)
        {
            AuctionContext db = new AuctionContext();

            var auction = db.Auctions.Find(bid.AuctionId);
            if (auction == null)
            {
                ModelState.AddModelError("AuctionId", "Auction Not Found");
            }
            else if (auction.CurrentPrice >= bid.Amount)
            {
                ModelState.AddModelError("Amount", "Bid Amount Less then the current Amount");
            }
            else
            {
                bid.UserName = User.Identity.Name;
                db.Bids.Add(bid);
                auction.CurrentPrice = bid.Amount;
                db.SaveChanges();
            }
            if (!Request.IsAjaxRequest())
                return RedirectToAction("FindingBy", new { id = bid.AuctionId });

            return Json(new
            {
                CurrentPrice = bid.Amount.ToString("C"),
                BidCount = auction.Bidcount
            });


        }
    }
}

AuctionModule/Views/Auctions/Auction.cshtml
@model AuctionModule.Models.Auction
@{
    ViewBag.Title = "Auction";
}
<h2>Auction</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category, (SelectList)ViewBag.cate, " -Select Your Category-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StartPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartPrice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AuctionModule/Views/Auctions/FindingBy.cshtml
@using AuctionModule.Models
@model AuctionModule.Models.Auction
@{
    ViewBag.Title = "FindingBy";
    var auction = new Auction();
}
<div class="auction">
    <h3>@Model.Title</h3>
    <div class="detail">
        <p>Starting Time:@Model.StartTime.ToString("g")</p>
        <p>End Time:@Model.EndTime.ToString("g")</p>
        <p>Start Price:@Model.StartPrice.ToString("C")</p>
        <p class="curr-price">
            Current Price:
            @if (Model.CurrentPrice == null)
            {
                @:[No Bid]
            }
            else
            {
                <span>@Model.CurrentPrice.Value.ToString("C")</span>
                <span>[@Model.Bidcount bids]</span>
            }
        </p>
        @if (Model.ImageUrl != null)
        {
            <img src="@Url.Content(Model.ImageUrl)" alt="@auction.Title" />
        }
        <div class="description">
            @Model.Description
        </div>
    </div>
</div>
<p>
    @using (Html.BeginForm("Bid", "Auctions"))
    {
        var lowestBid = Model.CurrentPrice.GetValueOrDefault(Model.StartPrice) + 1;
        <span>
            Bid:$  @Html.TextBox("amount", lowestBid)
            @Html.ValidationMessage("amount")
        </span>
        @Html.Hidden("auctionId", auction.Id)
        <input type="submit" value="Bid" class="post-bid" />

    }
</p>
<script id="templateofid" type="application/html-template">
    <p class="curr-price">
        <span>Current Price:{{CurrentPrice}}</span>
        <span>BidsCount:{{BidCount}}bids</span>
    </p>
</script>
@section script
{
    <script type="text/javascript">
        $(function() {
            $('.post-bid').on("click",
                function() {
                    var form = $(this).parent("form");

                    $.ajax({
                        type: "POST",
                        url: form.attr('action'),
                        data: form.serialize()

                    }).success(function(data) {
                        var template = $('#templateofid').clone().html();
                        var html = template.replace('{{CurrentPrice}}', data.CurrentPrice)
                            .replace('{{BidCount}}', data.BidCount);

                        $('.curr-price').replaceWith(html);
                    }).error(function() {
                        alert("Your Bid has been rejected");
                    });
                    return false;
                });
        });
    </script>
}

AuctionModule/Views/Auctions/Index.cshtml
@model IEnumerable<AuctionModule.Models.Auction>
@{
    ViewBag.Title = "Index";

    var auction = new AuctionModule.Models.Auction()
    {
        Title = "Mobiles",
        Description = "This is Smart Mobile For You",
        StartPrice = 1.00m,
        CurrentPrice = null,
        StartTime = DateTime.Now,
        EndTime = DateTime.Now.AddDays(7)
    };
}
@Html.Partial("~/Views/Shared/_Slider.cshtml")
@*<div class="auction">
        <h3>@auction.Title</h3>
        <div class="detail">
            <p>Starting Time:@auction.StartTime.ToString("g")</p>
            <p>End Time:@auction.EndTime.ToString("g")</p>
            <p>Start Price:@auction.StartPrice.ToString("C")</p>
            <p>
                Start  Price:
                @if (auction.CurrentPrice == null)
                {
                    @:[No Bid]
                }
                else
                {
                    <span>@auction.CurrentPrice.Value.ToString("C")</span>
                }
            </p>
            @if (auction.ImageUrl != null)
            {
                <img src="@Url.Content(auction.ImageUrl)" alt="@auction.Title" />
            }
            <div class="description">
                @auction.Description
            </div>
        </div>
    </div>*@
@foreach (var item in Model)

{

    @Html.Partial("_AuctionSummery", item)
}

AuctionModule/Views/Auctions/_AuctionSummery.cshtml
@model AuctionModule.Models.Auction
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <div class="auction-title">
                <h4 class="title">@Model.Title</h4>
                <p class="end-time">@Model.EndTime.ToString("g")</p>
                <p class="curr-price">
                    @Model.CurrentPrice.GetValueOrDefault(Model.StartPrice).ToString("C")
                </p>
            </div>
        </div>
    </div>
</div>

AuctionModule/Views/Auctions/_CurrentPrice.cshtml
<p class="curr-price">
    <span>Current Price:@Model.CurrentPrice.ToString("C")</span>
    <span>BidsCount:[@Model.Bidcount bids]</span>
</p>

AuctionModule/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Auctions", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("script", required: false)
</body>
</html>

AuctionModule/Views/Shared/_Slider.cshtml
<link href="~/Content/img/flickity.min.css" rel="stylesheet" />
<style>



    .carousel-container {
        width: 70vw; /* Set The Container Value As Required */
        margin: auto;
    }

    .carousel-cell img {
        width: 70vw; /* Set same value as container if you want single image to fit container */
    }
</style>
<div class="carousel-container">
    <div class="main-carousel">
        <div class="carousel-cell"> <img src="~/Content/img/IM-Banners (1).jpg" /></div>
        <div class="carousel-cell"> <img src="~/Content/img/IM-Banners (2).jpg" /></div>
        <div class="carousel-cell"> <img src="~/Content/img/IM-Banners (3).jpg" /></div>
        <div class="carousel-cell"> <img src="~/Content/img/IM-Banners (5).jpg" /></div>
        <div class="carousel-cell"> <img src="~/Content/img/IM-Banners (6).jpg" /></div>
    </div>
</div>
<script src="~/Content/img/flickity.pkgd.min.js"></script>
<script>
    var elem = document.querySelector(".main-carousel");
    var flkty = new Flickity(elem, {
        autoPlay: 2500,
        draggable: false,
        cellAlign: 'center',
        contain: true,
        wrapAround: true,
        prevNextButtons: true,
        pageDots: true,
        pauseAutoPlayOnHover: false,
        initialIndex: 2, // Zero Based Index, Set First Slide
        percentPosition: false    //-- TRUE Only If You want your slider width in percenatge
    });
</script>